// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: authzed/api/v1/permission_service_ext.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReadRelationshipsResponseExt with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReadRelationshipsResponseExt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReadRelationshipsResponseExt with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReadRelationshipsResponseExtMultiError, or nil if none found.
func (m *ReadRelationshipsResponseExt) ValidateAll() error {
	return m.validate(true)
}

func (m *ReadRelationshipsResponseExt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetReadAt() == nil {
		err := ReadRelationshipsResponseExtValidationError{
			field:  "ReadAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetReadAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReadRelationshipsResponseExtValidationError{
					field:  "ReadAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReadRelationshipsResponseExtValidationError{
					field:  "ReadAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReadAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadRelationshipsResponseExtValidationError{
				field:  "ReadAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRelationship() == nil {
		err := ReadRelationshipsResponseExtValidationError{
			field:  "Relationship",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRelationship()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReadRelationshipsResponseExtValidationError{
					field:  "Relationship",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReadRelationshipsResponseExtValidationError{
					field:  "Relationship",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRelationship()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadRelationshipsResponseExtValidationError{
				field:  "Relationship",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAfterResultCursor()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReadRelationshipsResponseExtValidationError{
					field:  "AfterResultCursor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReadRelationshipsResponseExtValidationError{
					field:  "AfterResultCursor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAfterResultCursor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadRelationshipsResponseExtValidationError{
				field:  "AfterResultCursor",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReadRelationshipsResponseExtMultiError(errors)
	}

	return nil
}

// ReadRelationshipsResponseExtMultiError is an error wrapping multiple
// validation errors returned by ReadRelationshipsResponseExt.ValidateAll() if
// the designated constraints aren't met.
type ReadRelationshipsResponseExtMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReadRelationshipsResponseExtMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReadRelationshipsResponseExtMultiError) AllErrors() []error { return m }

// ReadRelationshipsResponseExtValidationError is the validation error returned
// by ReadRelationshipsResponseExt.Validate if the designated constraints
// aren't met.
type ReadRelationshipsResponseExtValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadRelationshipsResponseExtValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadRelationshipsResponseExtValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadRelationshipsResponseExtValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadRelationshipsResponseExtValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadRelationshipsResponseExtValidationError) ErrorName() string {
	return "ReadRelationshipsResponseExtValidationError"
}

// Error satisfies the builtin error interface
func (e ReadRelationshipsResponseExtValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadRelationshipsResponseExt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadRelationshipsResponseExtValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadRelationshipsResponseExtValidationError{}

// Validate checks the field values on WriteRelationshipsRequestExt with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WriteRelationshipsRequestExt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WriteRelationshipsRequestExt with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WriteRelationshipsRequestExtMultiError, or nil if none found.
func (m *WriteRelationshipsRequestExt) ValidateAll() error {
	return m.validate(true)
}

func (m *WriteRelationshipsRequestExt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetUpdates() {
		_, _ = idx, item

		if item == nil {
			err := WriteRelationshipsRequestExtValidationError{
				field:  fmt.Sprintf("Updates[%v]", idx),
				reason: "value is required",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WriteRelationshipsRequestExtValidationError{
						field:  fmt.Sprintf("Updates[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WriteRelationshipsRequestExtValidationError{
						field:  fmt.Sprintf("Updates[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WriteRelationshipsRequestExtValidationError{
					field:  fmt.Sprintf("Updates[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetOptionalPreconditions() {
		_, _ = idx, item

		if item == nil {
			err := WriteRelationshipsRequestExtValidationError{
				field:  fmt.Sprintf("OptionalPreconditions[%v]", idx),
				reason: "value is required",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WriteRelationshipsRequestExtValidationError{
						field:  fmt.Sprintf("OptionalPreconditions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WriteRelationshipsRequestExtValidationError{
						field:  fmt.Sprintf("OptionalPreconditions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WriteRelationshipsRequestExtValidationError{
					field:  fmt.Sprintf("OptionalPreconditions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return WriteRelationshipsRequestExtMultiError(errors)
	}

	return nil
}

// WriteRelationshipsRequestExtMultiError is an error wrapping multiple
// validation errors returned by WriteRelationshipsRequestExt.ValidateAll() if
// the designated constraints aren't met.
type WriteRelationshipsRequestExtMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WriteRelationshipsRequestExtMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WriteRelationshipsRequestExtMultiError) AllErrors() []error { return m }

// WriteRelationshipsRequestExtValidationError is the validation error returned
// by WriteRelationshipsRequestExt.Validate if the designated constraints
// aren't met.
type WriteRelationshipsRequestExtValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WriteRelationshipsRequestExtValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WriteRelationshipsRequestExtValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WriteRelationshipsRequestExtValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WriteRelationshipsRequestExtValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WriteRelationshipsRequestExtValidationError) ErrorName() string {
	return "WriteRelationshipsRequestExtValidationError"
}

// Error satisfies the builtin error interface
func (e WriteRelationshipsRequestExtValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWriteRelationshipsRequestExt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WriteRelationshipsRequestExtValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WriteRelationshipsRequestExtValidationError{}
