---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches: ["*"]
  merge_group:
    types:
      - "checks_requested"
jobs:
  test:
    name: "Run Integration Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/action-spicedb@v1"
      - name: "Unit tests"
        run: "go run magefile.go test:integration"
